# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App911Interpreters' do
pod 'Firebase/Core'
pod 'Firebase/Messaging'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for App911Interpreters

  target 'App911Interpreters-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'App911InterpretersTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
